version: "3.3"
services:
  spa:
    image: ipvworkshop21.azurecr.io/workshop-ipv-containers_spa:latest
    environment: 
      - "REACT_APP_BACKEND_API=dotnet_api:60671"
    restart: always
    ports: 
      - "80:80"
    depends_on: 
      - dotnet_api
  dotnet_api:
    image: ipvworkshop21.azurecr.io/workshop-ipv-containers_dotnet_api:latest
    restart: always
    ports:
      - "60671:60671"
    environment: 
      ASPNETCORE_URLS: http://+:60671

